"use client";

// import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "@/lib/apollo";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
const font = Montserrat({ subsets: ["latin"] });


// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={font.className}>
            <ApolloProvider client={apolloClient}>
               <ToastContainer style={{ fontSize: "13px" }} />
               {children}
            </ApolloProvider>
         </body>
      </html>
   );
}
